load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "PressReleaseButton",
    module_name = "PressReleaseButton",
    srcs = glob(["**/*.swift"]),
    visibility = ["//Submodules/TinyComponentsKit:__pkg__"],
)
