load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "RoundedButton",
    module_name = "RoundedButton",
    srcs = glob(["**/*.swift"]),
    visibility = ["//Submodules/TinyComponentsKit:__pkg__"],
    deps = [
        "//Submodules/TinyComponentsKit/Submodules/TenTenSwiftUI"
    ]
)
