load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "TenTenSwiftUI",
    module_name = "TenTenSwiftUI",
    srcs = glob(["**/*.swift"]),
    visibility = ["//Submodules/TinyComponentsKit:__subpackages__"],
)
